// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xueqiu.proto

package spider

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HotStockItem struct {
	Change               float64  `protobuf:"fixed64,1,opt,name=change,proto3" json:"change,omitempty"`
	Exchange             string   `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Current              float64  `protobuf:"fixed64,4,opt,name=current,proto3" json:"current,omitempty"`
	Increment            float64  `protobuf:"fixed64,5,opt,name=increment,proto3" json:"increment,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Percent              float64  `protobuf:"fixed64,7,opt,name=percent,proto3" json:"percent,omitempty"`
	Type                 int32    `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	Value                float64  `protobuf:"fixed64,9,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HotStockItem) Reset()         { *m = HotStockItem{} }
func (m *HotStockItem) String() string { return proto.CompactTextString(m) }
func (*HotStockItem) ProtoMessage()    {}
func (*HotStockItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_7897fe1345918203, []int{0}
}

func (m *HotStockItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotStockItem.Unmarshal(m, b)
}
func (m *HotStockItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotStockItem.Marshal(b, m, deterministic)
}
func (m *HotStockItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotStockItem.Merge(m, src)
}
func (m *HotStockItem) XXX_Size() int {
	return xxx_messageInfo_HotStockItem.Size(m)
}
func (m *HotStockItem) XXX_DiscardUnknown() {
	xxx_messageInfo_HotStockItem.DiscardUnknown(m)
}

var xxx_messageInfo_HotStockItem proto.InternalMessageInfo

func (m *HotStockItem) GetChange() float64 {
	if m != nil {
		return m.Change
	}
	return 0
}

func (m *HotStockItem) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *HotStockItem) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *HotStockItem) GetCurrent() float64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func (m *HotStockItem) GetIncrement() float64 {
	if m != nil {
		return m.Increment
	}
	return 0
}

func (m *HotStockItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HotStockItem) GetPercent() float64 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *HotStockItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *HotStockItem) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type HotStockList struct {
	GlobalH1             []*HotStockItem `protobuf:"bytes,1,rep,name=global_h1,json=globalH1,proto3" json:"global_h1,omitempty"`
	GlobalH24            []*HotStockItem `protobuf:"bytes,2,rep,name=global_h24,json=globalH24,proto3" json:"global_h24,omitempty"`
	AshareH1             []*HotStockItem `protobuf:"bytes,3,rep,name=ashare_h1,json=ashareH1,proto3" json:"ashare_h1,omitempty"`
	AshareH24            []*HotStockItem `protobuf:"bytes,4,rep,name=ashare_h24,json=ashareH24,proto3" json:"ashare_h24,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HotStockList) Reset()         { *m = HotStockList{} }
func (m *HotStockList) String() string { return proto.CompactTextString(m) }
func (*HotStockList) ProtoMessage()    {}
func (*HotStockList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7897fe1345918203, []int{1}
}

func (m *HotStockList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HotStockList.Unmarshal(m, b)
}
func (m *HotStockList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HotStockList.Marshal(b, m, deterministic)
}
func (m *HotStockList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HotStockList.Merge(m, src)
}
func (m *HotStockList) XXX_Size() int {
	return xxx_messageInfo_HotStockList.Size(m)
}
func (m *HotStockList) XXX_DiscardUnknown() {
	xxx_messageInfo_HotStockList.DiscardUnknown(m)
}

var xxx_messageInfo_HotStockList proto.InternalMessageInfo

func (m *HotStockList) GetGlobalH1() []*HotStockItem {
	if m != nil {
		return m.GlobalH1
	}
	return nil
}

func (m *HotStockList) GetGlobalH24() []*HotStockItem {
	if m != nil {
		return m.GlobalH24
	}
	return nil
}

func (m *HotStockList) GetAshareH1() []*HotStockItem {
	if m != nil {
		return m.AshareH1
	}
	return nil
}

func (m *HotStockList) GetAshareH24() []*HotStockItem {
	if m != nil {
		return m.AshareH24
	}
	return nil
}

// 分红配送
type Bonus struct {
	AshareExDividendDate int64    `protobuf:"varint,1,opt,name=ashare_ex_dividend_date,json=ashareExDividendDate,proto3" json:"ashare_ex_dividend_date,omitempty"`
	CancleDividendDate   int64    `protobuf:"varint,2,opt,name=cancle_dividend_date,json=cancleDividendDate,proto3" json:"cancle_dividend_date,omitempty"`
	DividendDate         int64    `protobuf:"varint,3,opt,name=dividend_date,json=dividendDate,proto3" json:"dividend_date,omitempty"`
	DividendYear         string   `protobuf:"bytes,4,opt,name=dividend_year,json=dividendYear,proto3" json:"dividend_year,omitempty"`
	EquityDate           int64    `protobuf:"varint,5,opt,name=equity_date,json=equityDate,proto3" json:"equity_date,omitempty"`
	ExDividendDate       int64    `protobuf:"varint,6,opt,name=ex_dividend_date,json=exDividendDate,proto3" json:"ex_dividend_date,omitempty"`
	PlanExplain          string   `protobuf:"bytes,7,opt,name=plan_explain,json=planExplain,proto3" json:"plan_explain,omitempty"`
	DividendCash         float64  `protobuf:"fixed64,8,opt,name=dividend_cash,json=dividendCash,proto3" json:"dividend_cash,omitempty"`
	DividendShare        float64  `protobuf:"fixed64,9,opt,name=dividend_share,json=dividendShare,proto3" json:"dividend_share,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bonus) Reset()         { *m = Bonus{} }
func (m *Bonus) String() string { return proto.CompactTextString(m) }
func (*Bonus) ProtoMessage()    {}
func (*Bonus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7897fe1345918203, []int{2}
}

func (m *Bonus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bonus.Unmarshal(m, b)
}
func (m *Bonus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bonus.Marshal(b, m, deterministic)
}
func (m *Bonus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bonus.Merge(m, src)
}
func (m *Bonus) XXX_Size() int {
	return xxx_messageInfo_Bonus.Size(m)
}
func (m *Bonus) XXX_DiscardUnknown() {
	xxx_messageInfo_Bonus.DiscardUnknown(m)
}

var xxx_messageInfo_Bonus proto.InternalMessageInfo

func (m *Bonus) GetAshareExDividendDate() int64 {
	if m != nil {
		return m.AshareExDividendDate
	}
	return 0
}

func (m *Bonus) GetCancleDividendDate() int64 {
	if m != nil {
		return m.CancleDividendDate
	}
	return 0
}

func (m *Bonus) GetDividendDate() int64 {
	if m != nil {
		return m.DividendDate
	}
	return 0
}

func (m *Bonus) GetDividendYear() string {
	if m != nil {
		return m.DividendYear
	}
	return ""
}

func (m *Bonus) GetEquityDate() int64 {
	if m != nil {
		return m.EquityDate
	}
	return 0
}

func (m *Bonus) GetExDividendDate() int64 {
	if m != nil {
		return m.ExDividendDate
	}
	return 0
}

func (m *Bonus) GetPlanExplain() string {
	if m != nil {
		return m.PlanExplain
	}
	return ""
}

func (m *Bonus) GetDividendCash() float64 {
	if m != nil {
		return m.DividendCash
	}
	return 0
}

func (m *Bonus) GetDividendShare() float64 {
	if m != nil {
		return m.DividendShare
	}
	return 0
}

type BonusList struct {
	List                 []*Bonus `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BonusList) Reset()         { *m = BonusList{} }
func (m *BonusList) String() string { return proto.CompactTextString(m) }
func (*BonusList) ProtoMessage()    {}
func (*BonusList) Descriptor() ([]byte, []int) {
	return fileDescriptor_7897fe1345918203, []int{3}
}

func (m *BonusList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BonusList.Unmarshal(m, b)
}
func (m *BonusList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BonusList.Marshal(b, m, deterministic)
}
func (m *BonusList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BonusList.Merge(m, src)
}
func (m *BonusList) XXX_Size() int {
	return xxx_messageInfo_BonusList.Size(m)
}
func (m *BonusList) XXX_DiscardUnknown() {
	xxx_messageInfo_BonusList.DiscardUnknown(m)
}

var xxx_messageInfo_BonusList proto.InternalMessageInfo

func (m *BonusList) GetList() []*Bonus {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*HotStockItem)(nil), "goshare.spider.HotStockItem")
	proto.RegisterType((*HotStockList)(nil), "goshare.spider.HotStockList")
	proto.RegisterType((*Bonus)(nil), "goshare.spider.Bonus")
	proto.RegisterType((*BonusList)(nil), "goshare.spider.BonusList")
}

func init() { proto.RegisterFile("xueqiu.proto", fileDescriptor_7897fe1345918203) }

var fileDescriptor_7897fe1345918203 = []byte{
	// 508 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x4f, 0x6b, 0xdb, 0x4c,
	0x10, 0xc6, 0x91, 0xff, 0xc5, 0x1a, 0xfb, 0x35, 0x2f, 0x8b, 0xdb, 0x8a, 0x12, 0xa8, 0xeb, 0x52,
	0x70, 0x0f, 0xb5, 0x1b, 0xc7, 0x29, 0x94, 0xde, 0xd2, 0x04, 0x5c, 0xe8, 0x49, 0x39, 0xb5, 0x17,
	0xb3, 0x96, 0x06, 0x69, 0x89, 0xbc, 0xab, 0x48, 0x2b, 0x63, 0x7f, 0xe5, 0x9e, 0x7b, 0x2e, 0x65,
	0x67, 0xd7, 0x76, 0x9c, 0x52, 0xf0, 0x6d, 0x67, 0xe6, 0xf7, 0x3c, 0xa3, 0x9d, 0x1d, 0x41, 0x77,
	0x53, 0xe1, 0x83, 0xa8, 0xc6, 0x79, 0xa1, 0xb4, 0x62, 0xbd, 0x44, 0x95, 0x29, 0x2f, 0x70, 0x5c,
	0xe6, 0x22, 0xc6, 0x62, 0xf8, 0xd3, 0x83, 0xee, 0x5c, 0xe9, 0x3b, 0xad, 0xa2, 0xfb, 0xaf, 0x1a,
	0x57, 0xec, 0x39, 0xb4, 0xa2, 0x94, 0xcb, 0x04, 0x03, 0x6f, 0xe0, 0x8d, 0xbc, 0xd0, 0x45, 0xec,
	0x25, 0xb4, 0x71, 0xe3, 0x2a, 0xb5, 0x81, 0x37, 0xf2, 0xc3, 0x7d, 0x6c, 0x34, 0xe5, 0x76, 0xb5,
	0x54, 0x59, 0x50, 0xa7, 0x8a, 0x8b, 0x58, 0x00, 0x67, 0x51, 0x55, 0x14, 0x28, 0x75, 0xd0, 0x20,
	0xb3, 0x5d, 0xc8, 0xce, 0xc1, 0x17, 0x32, 0x2a, 0x70, 0x65, 0x6a, 0x4d, 0xaa, 0x1d, 0x12, 0x8c,
	0x41, 0x43, 0xf2, 0x15, 0x06, 0x2d, 0x72, 0xa3, 0xb3, 0xf1, 0xca, 0xb1, 0x88, 0x0c, 0x7f, 0x66,
	0xbd, 0x5c, 0x68, 0x68, 0xbd, 0xcd, 0x31, 0x68, 0x0f, 0xbc, 0x51, 0x33, 0xa4, 0x33, 0xeb, 0x43,
	0x73, 0xcd, 0xb3, 0x0a, 0x03, 0x9f, 0x58, 0x1b, 0x0c, 0x7f, 0x3f, 0xba, 0xec, 0x37, 0x51, 0x6a,
	0xf6, 0x09, 0xfc, 0x24, 0x53, 0x4b, 0x9e, 0x2d, 0xd2, 0x8b, 0xc0, 0x1b, 0xd4, 0x47, 0x9d, 0xe9,
	0xf9, 0xf8, 0x78, 0x42, 0xe3, 0xc7, 0xd3, 0x09, 0xdb, 0x16, 0x9f, 0x5f, 0xb0, 0xcf, 0x00, 0x3b,
	0xe9, 0x74, 0x16, 0xd4, 0x4e, 0xd0, 0xba, 0x56, 0xf3, 0xe9, 0xcc, 0xf4, 0xe5, 0x04, 0x9a, 0xbe,
	0xf5, 0x53, 0xfa, 0x5a, 0xdc, 0xf6, 0xdd, 0x49, 0xa7, 0xb3, 0xa0, 0x71, 0x4a, 0x5f, 0xa7, 0x9d,
	0xce, 0x86, 0xbf, 0x6a, 0xd0, 0xbc, 0x56, 0xb2, 0x2a, 0xd9, 0x15, 0xbc, 0x70, 0x36, 0xb8, 0x59,
	0xc4, 0x62, 0x2d, 0x62, 0x94, 0xf1, 0x22, 0xe6, 0xda, 0xbe, 0x7b, 0x3d, 0xec, 0xdb, 0xf2, 0xed,
	0xe6, 0xc6, 0x15, 0x6f, 0xb8, 0x46, 0xf6, 0x01, 0xfa, 0x11, 0x97, 0x51, 0x86, 0x4f, 0x34, 0x35,
	0xd2, 0x30, 0x5b, 0x3b, 0x52, 0xbc, 0x81, 0xff, 0x8e, 0xd1, 0x3a, 0xa1, 0xdd, 0xf8, 0x5f, 0xd0,
	0x16, 0x79, 0x41, 0xeb, 0xe2, 0x1f, 0xa0, 0xef, 0xc8, 0x0b, 0xf6, 0x0a, 0x3a, 0xf8, 0x50, 0x09,
	0xbd, 0xb5, 0x3e, 0x4d, 0xf2, 0x01, 0x9b, 0x22, 0x97, 0x11, 0xfc, 0xff, 0xd7, 0x65, 0x5a, 0x44,
	0xf5, 0xf0, 0xf8, 0x1a, 0xaf, 0xa1, 0x9b, 0x67, 0x5c, 0x2e, 0x70, 0x93, 0x67, 0x5c, 0x48, 0xda,
	0x28, 0x3f, 0xec, 0x98, 0xdc, 0xad, 0x4d, 0x1d, 0x7d, 0x52, 0xc4, 0xcb, 0x94, 0xd6, 0xcb, 0x3b,
	0x7c, 0xd2, 0x17, 0x5e, 0xa6, 0xec, 0x2d, 0xf4, 0xf6, 0x10, 0x8d, 0xcb, 0xed, 0xdb, 0x5e, 0x7a,
	0x67, 0x92, 0xc3, 0x8f, 0xe0, 0xd3, 0xd4, 0x69, 0xe7, 0xde, 0x41, 0x23, 0x13, 0xa5, 0x76, 0xeb,
	0xf6, 0xec, 0xe9, 0xd3, 0x11, 0x18, 0x12, 0x72, 0x7d, 0xf5, 0xe3, 0x32, 0x11, 0x3a, 0xad, 0x96,
	0xe3, 0x48, 0xad, 0x26, 0x21, 0x5f, 0xa3, 0x9c, 0x57, 0x6a, 0x92, 0xa8, 0xf7, 0xf4, 0x33, 0x4f,
	0x4a, 0xf3, 0xc6, 0xee, 0x9c, 0xdf, 0x27, 0x13, 0x6b, 0xb1, 0x6c, 0x51, 0xe6, 0xf2, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0f, 0xaf, 0xde, 0x34, 0xfa, 0x03, 0x00, 0x00,
}
