// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package pkg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuyStockRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity             string   `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	IsVirtual            bool     `protobuf:"varint,5,opt,name=is_virtual,json=isVirtual,proto3" json:"is_virtual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyStockRequest) Reset()         { *m = BuyStockRequest{} }
func (m *BuyStockRequest) String() string { return proto.CompactTextString(m) }
func (*BuyStockRequest) ProtoMessage()    {}
func (*BuyStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *BuyStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyStockRequest.Unmarshal(m, b)
}
func (m *BuyStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyStockRequest.Marshal(b, m, deterministic)
}
func (m *BuyStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyStockRequest.Merge(m, src)
}
func (m *BuyStockRequest) XXX_Size() int {
	return xxx_messageInfo_BuyStockRequest.Size(m)
}
func (m *BuyStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuyStockRequest proto.InternalMessageInfo

func (m *BuyStockRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BuyStockRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *BuyStockRequest) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *BuyStockRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BuyStockRequest) GetIsVirtual() bool {
	if m != nil {
		return m.IsVirtual
	}
	return false
}

type BuyStockResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance              float32  `protobuf:"fixed32,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyStockResponse) Reset()         { *m = BuyStockResponse{} }
func (m *BuyStockResponse) String() string { return proto.CompactTextString(m) }
func (*BuyStockResponse) ProtoMessage()    {}
func (*BuyStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *BuyStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyStockResponse.Unmarshal(m, b)
}
func (m *BuyStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyStockResponse.Marshal(b, m, deterministic)
}
func (m *BuyStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyStockResponse.Merge(m, src)
}
func (m *BuyStockResponse) XXX_Size() int {
	return xxx_messageInfo_BuyStockResponse.Size(m)
}
func (m *BuyStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuyStockResponse proto.InternalMessageInfo

func (m *BuyStockResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuyStockResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BuyStockResponse) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*BuyStockRequest)(nil), "goshare.spider.BuyStockRequest")
	proto.RegisterType((*BuyStockResponse)(nil), "goshare.spider.BuyStockResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0xd9, 0x3c, 0x4f, 0x5f, 0x32, 0x60, 0x95, 0x45, 0x34, 0x14, 0xc4, 0xd0, 0x53, 0x2e,
	0x26, 0xa0, 0x88, 0xf7, 0x1e, 0x44, 0x0f, 0x7a, 0xd8, 0xa2, 0x07, 0x2f, 0x21, 0x2f, 0x63, 0xba,
	0x34, 0xcd, 0xa6, 0x3b, 0xbb, 0x85, 0x7c, 0x0e, 0x3f, 0x8a, 0x5f, 0x50, 0x9a, 0xa6, 0x6a, 0x05,
	0x6f, 0x1e, 0x7f, 0x33, 0xc3, 0xec, 0x6f, 0xfe, 0x0b, 0x07, 0x84, 0x7a, 0x2d, 0x33, 0x0c, 0x6b,
	0xad, 0x8c, 0xe2, 0xa3, 0x42, 0xd1, 0x3c, 0xd1, 0x18, 0x52, 0x2d, 0x73, 0xd4, 0x93, 0x37, 0x06,
	0x87, 0x53, 0xdb, 0xcc, 0x8c, 0xca, 0x16, 0x02, 0x57, 0x16, 0xc9, 0xf0, 0x53, 0x18, 0x58, 0x42,
	0x1d, 0xcb, 0xdc, 0x63, 0x3e, 0x0b, 0x7a, 0xa2, 0xbf, 0xc1, 0xfb, 0x9c, 0x9f, 0x40, 0x9f, 0x9a,
	0x65, 0xaa, 0x4a, 0xcf, 0xf1, 0x59, 0xe0, 0x8a, 0x8e, 0xf8, 0x18, 0x86, 0x2b, 0x9b, 0x54, 0x46,
	0x9a, 0xc6, 0xfb, 0xd7, 0x76, 0x3e, 0x99, 0x1f, 0x43, 0xaf, 0xd6, 0x32, 0x43, 0xef, 0xbf, 0xcf,
	0x02, 0x47, 0x6c, 0x81, 0x9f, 0x01, 0x48, 0x8a, 0xd7, 0x52, 0x1b, 0x9b, 0x94, 0x5e, 0xcf, 0x67,
	0xc1, 0x50, 0xb8, 0x92, 0x9e, 0xb7, 0x85, 0xc9, 0x13, 0x1c, 0x7d, 0x49, 0x51, 0xad, 0x2a, 0x42,
	0x3e, 0x02, 0xa7, 0x13, 0x72, 0x85, 0x23, 0xf3, 0xef, 0x96, 0xce, 0x9e, 0xa5, 0x07, 0x83, 0x34,
	0x29, 0x93, 0x2a, 0xc3, 0x56, 0xc6, 0x11, 0x3b, 0xbc, 0x7c, 0x67, 0xc0, 0xdb, 0xa5, 0xb7, 0xb2,
	0xda, 0x14, 0x66, 0x0d, 0x19, 0x5c, 0xf2, 0x07, 0x18, 0xee, 0x5e, 0xe3, 0xe7, 0xe1, 0x7e, 0x40,
	0xe1, 0x8f, 0x70, 0xc6, 0xfe, 0xef, 0x03, 0x9d, 0xe8, 0x23, 0xb8, 0x33, 0x2c, 0xcb, 0xbf, 0xda,
	0x37, 0xbd, 0x79, 0xb9, 0x2e, 0xa4, 0x99, 0xdb, 0x34, 0xcc, 0xd4, 0x32, 0x12, 0xc9, 0x1a, 0xab,
	0x3b, 0xab, 0xa2, 0x42, 0x5d, 0xb4, 0x5f, 0x1a, 0xd1, 0x66, 0x3a, 0x7e, 0xdd, 0x9e, 0x14, 0x53,
	0x7b, 0x53, 0x54, 0x2f, 0x8a, 0xb4, 0xdf, 0xf6, 0xaf, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc5,
	0xf4, 0x61, 0xc5, 0x03, 0x02, 0x00, 0x00,
}
