// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package stock_finance_system

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuyStockRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity             string   `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	IsVirtual            bool     `protobuf:"varint,5,opt,name=is_virtual,json=isVirtual,proto3" json:"is_virtual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyStockRequest) Reset()         { *m = BuyStockRequest{} }
func (m *BuyStockRequest) String() string { return proto.CompactTextString(m) }
func (*BuyStockRequest) ProtoMessage()    {}
func (*BuyStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *BuyStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyStockRequest.Unmarshal(m, b)
}
func (m *BuyStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyStockRequest.Marshal(b, m, deterministic)
}
func (m *BuyStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyStockRequest.Merge(m, src)
}
func (m *BuyStockRequest) XXX_Size() int {
	return xxx_messageInfo_BuyStockRequest.Size(m)
}
func (m *BuyStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuyStockRequest proto.InternalMessageInfo

func (m *BuyStockRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BuyStockRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *BuyStockRequest) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *BuyStockRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BuyStockRequest) GetIsVirtual() bool {
	if m != nil {
		return m.IsVirtual
	}
	return false
}

type BuyStockResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance              float32  `protobuf:"fixed32,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyStockResponse) Reset()         { *m = BuyStockResponse{} }
func (m *BuyStockResponse) String() string { return proto.CompactTextString(m) }
func (*BuyStockResponse) ProtoMessage()    {}
func (*BuyStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *BuyStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyStockResponse.Unmarshal(m, b)
}
func (m *BuyStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyStockResponse.Marshal(b, m, deterministic)
}
func (m *BuyStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyStockResponse.Merge(m, src)
}
func (m *BuyStockResponse) XXX_Size() int {
	return xxx_messageInfo_BuyStockResponse.Size(m)
}
func (m *BuyStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuyStockResponse proto.InternalMessageInfo

func (m *BuyStockResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BuyStockResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BuyStockResponse) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type SellStockRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity             string   `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	IsVirtual            bool     `protobuf:"varint,5,opt,name=is_virtual,json=isVirtual,proto3" json:"is_virtual,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellStockRequest) Reset()         { *m = SellStockRequest{} }
func (m *SellStockRequest) String() string { return proto.CompactTextString(m) }
func (*SellStockRequest) ProtoMessage()    {}
func (*SellStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{2}
}

func (m *SellStockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellStockRequest.Unmarshal(m, b)
}
func (m *SellStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellStockRequest.Marshal(b, m, deterministic)
}
func (m *SellStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellStockRequest.Merge(m, src)
}
func (m *SellStockRequest) XXX_Size() int {
	return xxx_messageInfo_SellStockRequest.Size(m)
}
func (m *SellStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SellStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SellStockRequest proto.InternalMessageInfo

func (m *SellStockRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SellStockRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SellStockRequest) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

func (m *SellStockRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SellStockRequest) GetIsVirtual() bool {
	if m != nil {
		return m.IsVirtual
	}
	return false
}

type SellStockResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance              float32  `protobuf:"fixed32,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellStockResponse) Reset()         { *m = SellStockResponse{} }
func (m *SellStockResponse) String() string { return proto.CompactTextString(m) }
func (*SellStockResponse) ProtoMessage()    {}
func (*SellStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{3}
}

func (m *SellStockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellStockResponse.Unmarshal(m, b)
}
func (m *SellStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellStockResponse.Marshal(b, m, deterministic)
}
func (m *SellStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellStockResponse.Merge(m, src)
}
func (m *SellStockResponse) XXX_Size() int {
	return xxx_messageInfo_SellStockResponse.Size(m)
}
func (m *SellStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SellStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SellStockResponse proto.InternalMessageInfo

func (m *SellStockResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SellStockResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *SellStockResponse) GetBalance() float32 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func init() {
	proto.RegisterType((*BuyStockRequest)(nil), "goshare.spider.BuyStockRequest")
	proto.RegisterType((*BuyStockResponse)(nil), "goshare.spider.BuyStockResponse")
	proto.RegisterType((*SellStockRequest)(nil), "goshare.spider.SellStockRequest")
	proto.RegisterType((*SellStockResponse)(nil), "goshare.spider.SellStockResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xcb, 0x4a, 0xfb, 0x40,
	0x14, 0xc6, 0x99, 0xfc, 0xff, 0xbd, 0xe4, 0x80, 0xb5, 0x0e, 0xa2, 0xb1, 0x20, 0xc6, 0xae, 0xb2,
	0x31, 0x05, 0x7d, 0x02, 0x2b, 0x88, 0x2e, 0x04, 0x99, 0x60, 0x17, 0x6e, 0x42, 0x2e, 0x63, 0x3a,
	0x34, 0xcd, 0xa4, 0x73, 0x29, 0xe4, 0x39, 0xf4, 0x71, 0x7c, 0x38, 0xc9, 0xa5, 0xb5, 0xad, 0xe8,
	0xca, 0x85, 0xbb, 0xf9, 0xe6, 0x7c, 0x1c, 0x7e, 0xdf, 0xe1, 0x83, 0x3d, 0x49, 0xc5, 0x92, 0x45,
	0xd4, 0xcd, 0x05, 0x57, 0x1c, 0xf7, 0x12, 0x2e, 0xa7, 0x81, 0xa0, 0xae, 0xcc, 0x59, 0x4c, 0xc5,
	0xf0, 0x15, 0xc1, 0xfe, 0x58, 0x17, 0x9e, 0xe2, 0xd1, 0x8c, 0xd0, 0x85, 0xa6, 0x52, 0xe1, 0x63,
	0xe8, 0x68, 0x49, 0x85, 0xcf, 0x62, 0x0b, 0xd9, 0xc8, 0x69, 0x91, 0x76, 0x29, 0xef, 0x63, 0x7c,
	0x04, 0x6d, 0x59, 0xcc, 0x43, 0x9e, 0x5a, 0x86, 0x8d, 0x1c, 0x93, 0x34, 0x0a, 0x0f, 0xa0, 0xbb,
	0xd0, 0x41, 0xa6, 0x98, 0x2a, 0xac, 0x7f, 0xd5, 0x64, 0xad, 0xf1, 0x21, 0xb4, 0x72, 0xc1, 0x22,
	0x6a, 0xfd, 0xb7, 0x91, 0x63, 0x90, 0x5a, 0xe0, 0x53, 0x00, 0x26, 0xfd, 0x25, 0x13, 0x4a, 0x07,
	0xa9, 0xd5, 0xb2, 0x91, 0xd3, 0x25, 0x26, 0x93, 0x93, 0xfa, 0x63, 0xf8, 0x04, 0xfd, 0x4f, 0x28,
	0x99, 0xf3, 0x4c, 0x52, 0xdc, 0x03, 0xa3, 0x01, 0x32, 0x89, 0xc1, 0xe2, 0x4d, 0x4a, 0x63, 0x8b,
	0xd2, 0x82, 0x4e, 0x18, 0xa4, 0x41, 0x16, 0xd1, 0x0a, 0xc6, 0x20, 0x2b, 0x39, 0x7c, 0x43, 0xd0,
	0xf7, 0x68, 0x9a, 0xfe, 0xb1, 0xb4, 0x13, 0x38, 0xd8, 0xa0, 0xfa, 0xb5, 0xb8, 0x97, 0xef, 0x08,
	0x4e, 0xaa, 0xa5, 0xb7, 0x2c, 0x2b, 0x3f, 0xbc, 0x42, 0x2a, 0x3a, 0xf7, 0xea, 0x3e, 0xe0, 0x07,
	0xe8, 0xae, 0x6e, 0x8c, 0xcf, 0xdc, 0xed, 0x5a, 0xb8, 0x3b, 0x95, 0x18, 0xd8, 0xdf, 0x1b, 0x1a,
	0xde, 0x47, 0x30, 0xd7, 0x21, 0xf0, 0x17, 0xfb, 0xee, 0xd5, 0x07, 0xe7, 0x3f, 0x38, 0xea, 0x8d,
	0xe3, 0x9b, 0xe7, 0xeb, 0x84, 0xa9, 0xa9, 0x0e, 0xdd, 0x88, 0xcf, 0x47, 0x24, 0x58, 0xd2, 0xec,
	0x4e, 0xf3, 0x51, 0xc2, 0x2f, 0xaa, 0x2a, 0x8f, 0x64, 0xe9, 0x6e, 0xde, 0xf9, 0x2c, 0xa9, 0xb5,
	0xff, 0x52, 0x67, 0xf5, 0x65, 0x15, 0x36, 0x6c, 0x57, 0xf3, 0xab, 0x8f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0x6f, 0x6a, 0x0f, 0x07, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StockFinanceSystemServiceClient is the client API for StockFinanceSystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StockFinanceSystemServiceClient interface {
	BuyStock(ctx context.Context, in *BuyStockRequest, opts ...grpc.CallOption) (*BuyStockResponse, error)
	SellStock(ctx context.Context, in *SellStockRequest, opts ...grpc.CallOption) (*SellStockResponse, error)
}

type stockFinanceSystemServiceClient struct {
	cc *grpc.ClientConn
}

func NewStockFinanceSystemServiceClient(cc *grpc.ClientConn) StockFinanceSystemServiceClient {
	return &stockFinanceSystemServiceClient{cc}
}

func (c *stockFinanceSystemServiceClient) BuyStock(ctx context.Context, in *BuyStockRequest, opts ...grpc.CallOption) (*BuyStockResponse, error) {
	out := new(BuyStockResponse)
	err := c.cc.Invoke(ctx, "/goshare.spider.StockFinanceSystemService/BuyStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stockFinanceSystemServiceClient) SellStock(ctx context.Context, in *SellStockRequest, opts ...grpc.CallOption) (*SellStockResponse, error) {
	out := new(SellStockResponse)
	err := c.cc.Invoke(ctx, "/goshare.spider.StockFinanceSystemService/SellStock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StockFinanceSystemServiceServer is the server API for StockFinanceSystemService service.
type StockFinanceSystemServiceServer interface {
	BuyStock(context.Context, *BuyStockRequest) (*BuyStockResponse, error)
	SellStock(context.Context, *SellStockRequest) (*SellStockResponse, error)
}

func RegisterStockFinanceSystemServiceServer(s *grpc.Server, srv StockFinanceSystemServiceServer) {
	s.RegisterService(&_StockFinanceSystemService_serviceDesc, srv)
}

func _StockFinanceSystemService_BuyStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockFinanceSystemServiceServer).BuyStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goshare.spider.StockFinanceSystemService/BuyStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockFinanceSystemServiceServer).BuyStock(ctx, req.(*BuyStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StockFinanceSystemService_SellStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StockFinanceSystemServiceServer).SellStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/goshare.spider.StockFinanceSystemService/SellStock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StockFinanceSystemServiceServer).SellStock(ctx, req.(*SellStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StockFinanceSystemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "goshare.spider.StockFinanceSystemService",
	HandlerType: (*StockFinanceSystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuyStock",
			Handler:    _StockFinanceSystemService_BuyStock_Handler,
		},
		{
			MethodName: "SellStock",
			Handler:    _StockFinanceSystemService_SellStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
