// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub/demo.proto

package hub

import (
	fmt "fmt"
	goshare "github.com/RavenHuo/go-proto/stock-proto/pkg/goshare"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 模拟环境的订单记录
type DemoOrder struct {
	TaId                 string                  `protobuf:"bytes,1,opt,name=ta_id,json=taId,proto3" json:"ta_id,omitempty"`
	BuId                 string                  `protobuf:"bytes,2,opt,name=bu_id,json=buId,proto3" json:"bu_id,omitempty"`
	FrontId              int32                   `protobuf:"varint,3,opt,name=front_id,json=frontId,proto3" json:"front_id,omitempty"`
	SessionId            int32                   `protobuf:"varint,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OrderRef             string                  `protobuf:"bytes,5,opt,name=order_ref,json=orderRef,proto3" json:"order_ref,omitempty"`
	Exchange             string                  `protobuf:"bytes,6,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol               string                  `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Product              string                  `protobuf:"bytes,8,opt,name=product,proto3" json:"product,omitempty"`
	Direction            int32                   `protobuf:"varint,9,opt,name=direction,proto3" json:"direction,omitempty"`
	Offset               int32                   `protobuf:"varint,10,opt,name=offset,proto3" json:"offset,omitempty"`
	Price                float64                 `protobuf:"fixed64,11,opt,name=price,proto3" json:"price,omitempty"`
	Volume               int32                   `protobuf:"varint,12,opt,name=volume,proto3" json:"volume,omitempty"`
	PriceTick            float64                 `protobuf:"fixed64,13,opt,name=price_tick,json=priceTick,proto3" json:"price_tick,omitempty"`
	Multiple             int32                   `protobuf:"varint,14,opt,name=multiple,proto3" json:"multiple,omitempty"`
	TradingDay           int32                   `protobuf:"varint,15,opt,name=trading_day,json=tradingDay,proto3" json:"trading_day,omitempty"`
	Status               int32                   `protobuf:"varint,16,opt,name=status,proto3" json:"status,omitempty"`
	DemoOrderId          string                  `protobuf:"bytes,17,opt,name=demo_order_id,json=demoOrderId,proto3" json:"demo_order_id,omitempty"`
	UpperLimit           float64                 `protobuf:"fixed64,18,opt,name=upper_limit,json=upperLimit,proto3" json:"upper_limit,omitempty"`
	LowerLimit           float64                 `protobuf:"fixed64,19,opt,name=lower_limit,json=lowerLimit,proto3" json:"lower_limit,omitempty"`
	MinLimitOrderVolume  int32                   `protobuf:"varint,20,opt,name=min_limit_order_volume,json=minLimitOrderVolume,proto3" json:"min_limit_order_volume,omitempty"`
	MinMarketOrderVolume int32                   `protobuf:"varint,21,opt,name=min_market_order_volume,json=minMarketOrderVolume,proto3" json:"min_market_order_volume,omitempty"`
	VolumeTraded         int32                   `protobuf:"varint,22,opt,name=volume_traded,json=volumeTraded,proto3" json:"volume_traded,omitempty"`
	VolumeCanceled       int32                   `protobuf:"varint,23,opt,name=volume_canceled,json=volumeCanceled,proto3" json:"volume_canceled,omitempty"`
	SendTradingDay       int32                   `protobuf:"varint,24,opt,name=send_trading_day,json=sendTradingDay,proto3" json:"send_trading_day,omitempty"`
	ProductType          int32                   `protobuf:"varint,25,opt,name=product_type,json=productType,proto3" json:"product_type,omitempty"`
	OrderSourceType      int32                   `protobuf:"varint,26,opt,name=order_source_type,json=orderSourceType,proto3" json:"order_source_type,omitempty"`
	PriceType            int32                   `protobuf:"varint,27,opt,name=price_type,json=priceType,proto3" json:"price_type,omitempty"`
	SendTime             int64                   `protobuf:"varint,28,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	TimeRule             []*goshare.MarketStatus `protobuf:"bytes,29,rep,name=time_rule,json=timeRule,proto3" json:"time_rule,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *DemoOrder) Reset()         { *m = DemoOrder{} }
func (m *DemoOrder) String() string { return proto.CompactTextString(m) }
func (*DemoOrder) ProtoMessage()    {}
func (*DemoOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_983becccff96becb, []int{0}
}

func (m *DemoOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DemoOrder.Unmarshal(m, b)
}
func (m *DemoOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DemoOrder.Marshal(b, m, deterministic)
}
func (m *DemoOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DemoOrder.Merge(m, src)
}
func (m *DemoOrder) XXX_Size() int {
	return xxx_messageInfo_DemoOrder.Size(m)
}
func (m *DemoOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_DemoOrder.DiscardUnknown(m)
}

var xxx_messageInfo_DemoOrder proto.InternalMessageInfo

func (m *DemoOrder) GetTaId() string {
	if m != nil {
		return m.TaId
	}
	return ""
}

func (m *DemoOrder) GetBuId() string {
	if m != nil {
		return m.BuId
	}
	return ""
}

func (m *DemoOrder) GetFrontId() int32 {
	if m != nil {
		return m.FrontId
	}
	return 0
}

func (m *DemoOrder) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *DemoOrder) GetOrderRef() string {
	if m != nil {
		return m.OrderRef
	}
	return ""
}

func (m *DemoOrder) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *DemoOrder) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *DemoOrder) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *DemoOrder) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *DemoOrder) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *DemoOrder) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *DemoOrder) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *DemoOrder) GetPriceTick() float64 {
	if m != nil {
		return m.PriceTick
	}
	return 0
}

func (m *DemoOrder) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *DemoOrder) GetTradingDay() int32 {
	if m != nil {
		return m.TradingDay
	}
	return 0
}

func (m *DemoOrder) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *DemoOrder) GetDemoOrderId() string {
	if m != nil {
		return m.DemoOrderId
	}
	return ""
}

func (m *DemoOrder) GetUpperLimit() float64 {
	if m != nil {
		return m.UpperLimit
	}
	return 0
}

func (m *DemoOrder) GetLowerLimit() float64 {
	if m != nil {
		return m.LowerLimit
	}
	return 0
}

func (m *DemoOrder) GetMinLimitOrderVolume() int32 {
	if m != nil {
		return m.MinLimitOrderVolume
	}
	return 0
}

func (m *DemoOrder) GetMinMarketOrderVolume() int32 {
	if m != nil {
		return m.MinMarketOrderVolume
	}
	return 0
}

func (m *DemoOrder) GetVolumeTraded() int32 {
	if m != nil {
		return m.VolumeTraded
	}
	return 0
}

func (m *DemoOrder) GetVolumeCanceled() int32 {
	if m != nil {
		return m.VolumeCanceled
	}
	return 0
}

func (m *DemoOrder) GetSendTradingDay() int32 {
	if m != nil {
		return m.SendTradingDay
	}
	return 0
}

func (m *DemoOrder) GetProductType() int32 {
	if m != nil {
		return m.ProductType
	}
	return 0
}

func (m *DemoOrder) GetOrderSourceType() int32 {
	if m != nil {
		return m.OrderSourceType
	}
	return 0
}

func (m *DemoOrder) GetPriceType() int32 {
	if m != nil {
		return m.PriceType
	}
	return 0
}

func (m *DemoOrder) GetSendTime() int64 {
	if m != nil {
		return m.SendTime
	}
	return 0
}

func (m *DemoOrder) GetTimeRule() []*goshare.MarketStatus {
	if m != nil {
		return m.TimeRule
	}
	return nil
}

func init() {
	proto.RegisterType((*DemoOrder)(nil), "goshare.hub.DemoOrder")
}

func init() { proto.RegisterFile("hub/demo.proto", fileDescriptor_983becccff96becb) }

var fileDescriptor_983becccff96becb = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x93, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0x86, 0xe1, 0x93, 0x38, 0xb6, 0xc6, 0xb9, 0x32, 0x37, 0xe6, 0x86, 0xe3, 0x93, 0xb3, 0xa8,
	0x51, 0xa0, 0x76, 0x91, 0xa0, 0x2f, 0xd0, 0x66, 0x51, 0x03, 0x2d, 0x0a, 0x28, 0x46, 0x17, 0xdd,
	0x08, 0x92, 0x38, 0xb6, 0x09, 0x8b, 0xa4, 0x40, 0x91, 0x69, 0xfd, 0x6c, 0x7d, 0xb9, 0x82, 0x43,
	0x39, 0x09, 0xba, 0xd3, 0xff, 0xff, 0xdf, 0x90, 0x9c, 0x21, 0x05, 0xfb, 0x4b, 0x5f, 0x4c, 0x04,
	0x2a, 0x33, 0xae, 0xad, 0x71, 0x86, 0x0d, 0x16, 0xa6, 0x59, 0xe6, 0x16, 0xc7, 0x4b, 0x5f, 0x5c,
	0xf2, 0x56, 0x4c, 0xa4, 0x6e, 0x9c, 0xf5, 0x0a, 0xb5, 0x8b, 0xd8, 0xed, 0xef, 0x1e, 0x24, 0x0f,
	0xa8, 0xcc, 0x37, 0x2b, 0xd0, 0xb2, 0x63, 0xe8, 0xba, 0x3c, 0x93, 0x82, 0x77, 0x86, 0x9d, 0x51,
	0x92, 0x6e, 0xbb, 0x7c, 0x2a, 0x82, 0x59, 0xf8, 0x60, 0xfe, 0x13, 0xcd, 0xc2, 0x4f, 0x05, 0xbb,
	0x80, 0xfe, 0xdc, 0x1a, 0xed, 0x82, 0xbf, 0x35, 0xec, 0x8c, 0xba, 0x69, 0x8f, 0xf4, 0x54, 0xb0,
	0x1b, 0x80, 0x06, 0x9b, 0x46, 0x1a, 0x1d, 0xc2, 0x6d, 0x0a, 0x93, 0xd6, 0x99, 0x0a, 0x76, 0x05,
	0x89, 0x09, 0x9b, 0x65, 0x16, 0xe7, 0xbc, 0x4b, 0x4b, 0xf6, 0xc9, 0x48, 0x71, 0xce, 0x2e, 0xa1,
	0x8f, 0xbf, 0xca, 0x65, 0xae, 0x17, 0xc8, 0x77, 0x62, 0xb6, 0xd1, 0xec, 0x0c, 0x76, 0x9a, 0xb5,
	0x2a, 0x4c, 0xc5, 0x7b, 0x94, 0xb4, 0x8a, 0x71, 0xe8, 0xd5, 0xd6, 0x08, 0x5f, 0x3a, 0xde, 0xa7,
	0x60, 0x23, 0xd9, 0x35, 0x24, 0x42, 0x5a, 0x2c, 0x9d, 0x34, 0x9a, 0x27, 0xf1, 0x20, 0xcf, 0x46,
	0x58, 0xcf, 0xcc, 0xe7, 0x0d, 0x3a, 0x0e, 0x14, 0xb5, 0x8a, 0x9d, 0x40, 0xb7, 0xb6, 0xb2, 0x44,
	0x3e, 0x18, 0x76, 0x46, 0x9d, 0x34, 0x8a, 0x40, 0x3f, 0x99, 0xca, 0x2b, 0xe4, 0xbb, 0x91, 0x8e,
	0x2a, 0x74, 0x4b, 0x40, 0xe6, 0x64, 0xb9, 0xe2, 0x7b, 0x54, 0x92, 0x90, 0x33, 0x93, 0xe5, 0x2a,
	0x34, 0xa4, 0x7c, 0xe5, 0x64, 0x5d, 0x21, 0xdf, 0xa7, 0xc2, 0x67, 0xcd, 0xfe, 0x85, 0x81, 0xb3,
	0xb9, 0x90, 0x7a, 0x91, 0x89, 0x7c, 0xcd, 0x0f, 0x28, 0x86, 0xd6, 0x7a, 0xc8, 0xd7, 0xd4, 0xb1,
	0xcb, 0x9d, 0x6f, 0xf8, 0x61, 0xdc, 0x33, 0x2a, 0x76, 0x0b, 0x7b, 0xe1, 0xa6, 0xb3, 0x38, 0x47,
	0x29, 0xf8, 0x11, 0xf5, 0x3d, 0x10, 0x9b, 0x8b, 0x9c, 0x8a, 0xb0, 0xb8, 0xaf, 0x6b, 0xb4, 0x59,
	0x25, 0x95, 0x74, 0x9c, 0xd1, 0xc1, 0x80, 0xac, 0x2f, 0xc1, 0x09, 0x40, 0x65, 0x7e, 0x3e, 0x03,
	0xc7, 0x11, 0x20, 0x2b, 0x02, 0xf7, 0x70, 0xa6, 0xa4, 0x8e, 0x71, 0xbb, 0x55, 0x3b, 0x81, 0x13,
	0x3a, 0xcd, 0xb1, 0x92, 0x9a, 0x48, 0xda, 0xf2, 0x7b, 0x1c, 0xc7, 0x07, 0x38, 0x0f, 0x45, 0x2a,
	0xb7, 0x2b, 0xfc, 0xab, 0xea, 0x94, 0xaa, 0x4e, 0x94, 0xd4, 0x5f, 0x29, 0x7d, 0x5d, 0xf6, 0x3f,
	0xec, 0x45, 0x2a, 0x0b, 0xed, 0xa3, 0xe0, 0x67, 0x04, 0xef, 0x46, 0x73, 0x46, 0x1e, 0x7b, 0x03,
	0x07, 0x2d, 0x54, 0xe6, 0xba, 0xc4, 0x0a, 0x05, 0x3f, 0x27, 0x6c, 0x3f, 0xda, 0x9f, 0x5a, 0x97,
	0x8d, 0xe0, 0xb0, 0x41, 0x2d, 0xb2, 0xd7, 0xd3, 0xe5, 0x91, 0x0c, 0xfe, 0xec, 0x65, 0xc2, 0xff,
	0xc1, 0x6e, 0xfb, 0x58, 0x32, 0xb7, 0xae, 0x91, 0x5f, 0x10, 0x35, 0x68, 0xbd, 0xd9, 0xba, 0x46,
	0xf6, 0x16, 0x8e, 0x62, 0x1b, 0x8d, 0xf1, 0x36, 0xdc, 0x73, 0xe0, 0x2e, 0x89, 0x3b, 0xa0, 0xe0,
	0x91, 0x7c, 0x62, 0x5f, 0x1e, 0x43, 0x80, 0xae, 0xe2, 0x8b, 0x8b, 0x8f, 0x21, 0xc4, 0x57, 0x90,
	0xc4, 0x73, 0x49, 0x85, 0xfc, 0x7a, 0xd8, 0x19, 0x6d, 0xa5, 0x7d, 0x3a, 0x90, 0x54, 0xc8, 0xee,
	0x20, 0x09, 0x7e, 0x66, 0x7d, 0x85, 0xfc, 0x66, 0xb8, 0x35, 0x1a, 0xdc, 0x9d, 0x8e, 0x37, 0x3f,
	0x71, 0x9c, 0xd8, 0x23, 0x5d, 0x7f, 0xda, 0x0f, 0x5c, 0xea, 0x2b, 0xfc, 0x78, 0xf7, 0xe3, 0xfd,
	0x42, 0xba, 0xa5, 0x2f, 0xc6, 0xa5, 0x51, 0x93, 0x34, 0x7f, 0x42, 0xfd, 0xd9, 0x9b, 0xc9, 0xc2,
	0xbc, 0xa3, 0xbf, 0x7b, 0xd2, 0x38, 0x53, 0xae, 0xda, 0xef, 0x7a, 0xb5, 0x98, 0x2c, 0x7d, 0x51,
	0xec, 0x90, 0xbc, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0xcc, 0x15, 0x34, 0x65, 0x31, 0x04, 0x00,
	0x00,
}
