// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: food_service.proto

package merry_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListFoodReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page  int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Name  string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ListFoodReq) Reset() {
	*x = ListFoodReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFoodReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodReq) ProtoMessage() {}

func (x *ListFoodReq) ProtoReflect() protoreflect.Message {
	mi := &file_food_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodReq.ProtoReflect.Descriptor instead.
func (*ListFoodReq) Descriptor() ([]byte, []int) {
	return file_food_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListFoodReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFoodReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFoodReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListFoodResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total int32   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	List  []*Food `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ListFoodResp) Reset() {
	*x = ListFoodResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFoodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodResp) ProtoMessage() {}

func (x *ListFoodResp) ProtoReflect() protoreflect.Message {
	mi := &file_food_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodResp.ProtoReflect.Descriptor instead.
func (*ListFoodResp) Descriptor() ([]byte, []int) {
	return file_food_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListFoodResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFoodResp) GetList() []*Food {
	if x != nil {
		return x.List
	}
	return nil
}

type Food struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Introduce string `protobuf:"bytes,3,opt,name=introduce,proto3" json:"introduce,omitempty"`
	Pic       string `protobuf:"bytes,4,opt,name=pic,proto3" json:"pic,omitempty"`
	Video     string `protobuf:"bytes,5,opt,name=video,proto3" json:"video,omitempty"`
}

func (x *Food) Reset() {
	*x = Food{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_food_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_food_service_proto_rawDescGZIP(), []int{2}
}

func (x *Food) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Food) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Food) GetIntroduce() string {
	if x != nil {
		return x.Introduce
	}
	return ""
}

func (x *Food) GetPic() string {
	if x != nil {
		return x.Pic
	}
	return ""
}

func (x *Food) GetVideo() string {
	if x != nil {
		return x.Video
	}
	return ""
}

type CreateOrUpdateFoodResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateOrUpdateFoodResp) Reset() {
	*x = CreateOrUpdateFoodResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrUpdateFoodResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrUpdateFoodResp) ProtoMessage() {}

func (x *CreateOrUpdateFoodResp) ProtoReflect() protoreflect.Message {
	mi := &file_food_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrUpdateFoodResp.ProtoReflect.Descriptor instead.
func (*CreateOrUpdateFoodResp) Descriptor() ([]byte, []int) {
	return file_food_service_proto_rawDescGZIP(), []int{3}
}

type RandomOneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RandomOneReq) Reset() {
	*x = RandomOneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_food_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RandomOneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RandomOneReq) ProtoMessage() {}

func (x *RandomOneReq) ProtoReflect() protoreflect.Message {
	mi := &file_food_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RandomOneReq.ProtoReflect.Descriptor instead.
func (*RandomOneReq) Descriptor() ([]byte, []int) {
	return file_food_service_proto_rawDescGZIP(), []int{4}
}

var File_food_service_proto protoreflect.FileDescriptor

var file_food_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x4b, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x4c, 0x0a, 0x0c, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x26, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x70, 0x0a,
	0x04, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x74,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e,
	0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x63, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x22,
	0x18, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x32, 0xdd, 0x01, 0x0a, 0x0b, 0x46, 0x6f,
	0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x19, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71,
	0x1a, 0x1a, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x4e, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6f,
	0x6f, 0x64, 0x12, 0x12, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x1a, 0x24, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x09,
	0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4f, 0x6e, 0x65, 0x12, 0x1a, 0x2e, 0x66, 0x6f, 0x6f, 0x64,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x4f,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x52, 0x61, 0x76, 0x65, 0x6e, 0x48, 0x75, 0x6f,
	0x2f, 0x66, 0x72, 0x65, 0x65, 0x77, 0x68, 0x65, 0x65, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x6d, 0x65, 0x72, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_food_service_proto_rawDescOnce sync.Once
	file_food_service_proto_rawDescData = file_food_service_proto_rawDesc
)

func file_food_service_proto_rawDescGZIP() []byte {
	file_food_service_proto_rawDescOnce.Do(func() {
		file_food_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_food_service_proto_rawDescData)
	})
	return file_food_service_proto_rawDescData
}

var file_food_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_food_service_proto_goTypes = []interface{}{
	(*ListFoodReq)(nil),            // 0: food_service.ListFoodReq
	(*ListFoodResp)(nil),           // 1: food_service.ListFoodResp
	(*Food)(nil),                   // 2: food_service.Food
	(*CreateOrUpdateFoodResp)(nil), // 3: food_service.CreateOrUpdateFoodResp
	(*RandomOneReq)(nil),           // 4: food_service.RandomOneReq
}
var file_food_service_proto_depIdxs = []int32{
	2, // 0: food_service.ListFoodResp.list:type_name -> food_service.Food
	0, // 1: food_service.FoodService.ListFood:input_type -> food_service.ListFoodReq
	2, // 2: food_service.FoodService.CreateOrUpdateFood:input_type -> food_service.Food
	4, // 3: food_service.FoodService.RandomOne:input_type -> food_service.RandomOneReq
	1, // 4: food_service.FoodService.ListFood:output_type -> food_service.ListFoodResp
	3, // 5: food_service.FoodService.CreateOrUpdateFood:output_type -> food_service.CreateOrUpdateFoodResp
	2, // 6: food_service.FoodService.RandomOne:output_type -> food_service.Food
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_food_service_proto_init() }
func file_food_service_proto_init() {
	if File_food_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_food_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFoodReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFoodResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Food); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrUpdateFoodResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_food_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RandomOneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_food_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_food_service_proto_goTypes,
		DependencyIndexes: file_food_service_proto_depIdxs,
		MessageInfos:      file_food_service_proto_msgTypes,
	}.Build()
	File_food_service_proto = out.File
	file_food_service_proto_rawDesc = nil
	file_food_service_proto_goTypes = nil
	file_food_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FoodServiceClient is the client API for FoodService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FoodServiceClient interface {
	ListFood(ctx context.Context, in *ListFoodReq, opts ...grpc.CallOption) (*ListFoodResp, error)
	CreateOrUpdateFood(ctx context.Context, in *Food, opts ...grpc.CallOption) (*CreateOrUpdateFoodResp, error)
	RandomOne(ctx context.Context, in *RandomOneReq, opts ...grpc.CallOption) (*Food, error)
}

type foodServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodServiceClient(cc grpc.ClientConnInterface) FoodServiceClient {
	return &foodServiceClient{cc}
}

func (c *foodServiceClient) ListFood(ctx context.Context, in *ListFoodReq, opts ...grpc.CallOption) (*ListFoodResp, error) {
	out := new(ListFoodResp)
	err := c.cc.Invoke(ctx, "/food_service.FoodService/ListFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) CreateOrUpdateFood(ctx context.Context, in *Food, opts ...grpc.CallOption) (*CreateOrUpdateFoodResp, error) {
	out := new(CreateOrUpdateFoodResp)
	err := c.cc.Invoke(ctx, "/food_service.FoodService/CreateOrUpdateFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *foodServiceClient) RandomOne(ctx context.Context, in *RandomOneReq, opts ...grpc.CallOption) (*Food, error) {
	out := new(Food)
	err := c.cc.Invoke(ctx, "/food_service.FoodService/RandomOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodServiceServer is the server API for FoodService service.
type FoodServiceServer interface {
	ListFood(context.Context, *ListFoodReq) (*ListFoodResp, error)
	CreateOrUpdateFood(context.Context, *Food) (*CreateOrUpdateFoodResp, error)
	RandomOne(context.Context, *RandomOneReq) (*Food, error)
}

// UnimplementedFoodServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFoodServiceServer struct {
}

func (*UnimplementedFoodServiceServer) ListFood(context.Context, *ListFoodReq) (*ListFoodResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFood not implemented")
}
func (*UnimplementedFoodServiceServer) CreateOrUpdateFood(context.Context, *Food) (*CreateOrUpdateFoodResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateFood not implemented")
}
func (*UnimplementedFoodServiceServer) RandomOne(context.Context, *RandomOneReq) (*Food, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomOne not implemented")
}

func RegisterFoodServiceServer(s *grpc.Server, srv FoodServiceServer) {
	s.RegisterService(&_FoodService_serviceDesc, srv)
}

func _FoodService_ListFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFoodReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).ListFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/food_service.FoodService/ListFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).ListFood(ctx, req.(*ListFoodReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_CreateOrUpdateFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Food)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).CreateOrUpdateFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/food_service.FoodService/CreateOrUpdateFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).CreateOrUpdateFood(ctx, req.(*Food))
	}
	return interceptor(ctx, in, info, handler)
}

func _FoodService_RandomOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RandomOneReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).RandomOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/food_service.FoodService/RandomOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).RandomOne(ctx, req.(*RandomOneReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _FoodService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "food_service.FoodService",
	HandlerType: (*FoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFood",
			Handler:    _FoodService_ListFood_Handler,
		},
		{
			MethodName: "CreateOrUpdateFood",
			Handler:    _FoodService_CreateOrUpdateFood_Handler,
		},
		{
			MethodName: "RandomOne",
			Handler:    _FoodService_RandomOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food_service.proto",
}
