name: AUTO CI

on:
  push:
    branches:
      - main

jobs:
  auto_proto_ci:
    # 工作流程中的push_files作业运行在ubuntu-latest环境中，即Ubuntu操作系统的最新版本。
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        # 是一个官方提供的操作，它会自动检出仓库的代码，默认情况下会将代码检出到工作目录中。这个操作可以用于不同类型的仓库，包括 GitHub 仓库、GitLab 仓库等。
        uses: actions/checkout@v2

      # 安装 protoc
      - name: Install Protocol Buffers compiler
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16 # 替换为你希望使用的 Go 版本

      # 版本必须是1.3.5
      - name: Install protoc-gen-go
        run: |
          go get -u github.com/golang/protobuf/protoc-gen-go@v1.5.3

      - name: Execute Auto Build Shell Script
        run: |
          cd stock-proto
          sh make.sh

      - name: Commit And Push Change
        # 换行就用 |
        run: |
          git config --local user.email "965195920@qq.com"
          git config --local user.name "huoruiwen"
          git add -A
          git commit -m "AUTO CI"
          git push